-- MySQL Script generated by MySQL Workbench
-- Sat Apr 25 21:45:08 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`filme` (
  `idfilme` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `sinopse` TEXT NOT NULL,
  `faixa_etaria` INT NOT NULL,
  `duracao` INT NOT NULL,
  PRIMARY KEY (`idfilme`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cinema`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`sala` (
  `idsala` INT NOT NULL AUTO_INCREMENT,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`idsala`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cinema`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`sessao` (
  `idsessao` INT NOT NULL AUTO_INCREMENT,
  `idsala` INT NOT NULL,
  `idfilme` INT NOT NULL,
  `horario` TIME NOT NULL,
  `expiracao` DATETIME NOT NULL,
  PRIMARY KEY (`idsessao`),
  INDEX `idfilme_idx` (`idfilme` ASC),
  INDEX `idsala_idx` (`idsala` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cinema`.`ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`ingresso` (
  `idingresso` INT NOT NULL,
  `idsessao` INT NOT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idingresso`),
  INDEX `idsessai_idx` (`idsessao` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cinema`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`venda` (
  `idsessao` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsessao`, `data`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `cinema`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`venda` (
  `idsessao` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsessao`, `data`))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
