-- MySQL Script generated by MySQL Workbench
-- Sun Apr 26 22:25:57 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cinema` ;

-- -----------------------------------------------------
-- Schema cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cinema` ;

-- -----------------------------------------------------
-- Table `cinema`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`filme` (
  `idfilme` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `genero` VARCHAR(100) NOT NULL,
  `sinopse` TEXT NOT NULL,
  `faixa_etaria` INT NOT NULL,
  `duracao` INT NOT NULL,
  PRIMARY KEY (`idfilme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`sala` (
  `idsala` INT NOT NULL AUTO_INCREMENT,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`idsala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`sessao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`sessao` (
  `idsessao` INT NOT NULL AUTO_INCREMENT,
  `idsala` INT NOT NULL,
  `idfilme` INT NOT NULL,
  `horario` DATETIME NOT NULL,
  `expiracao` DATE NOT NULL,
  PRIMARY KEY (`idsessao`),
  INDEX `idfilme_idx` (`idfilme` ASC),
  INDEX `idsala_idx` (`idsala` ASC),
  FOREIGN KEY (`idfilme`) REFERENCES `cinema`.`filme` (`idfilme`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (`idsala`) REFERENCES `cinema`.`sala` (`idsala`) ON DELETE RESTRICT ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cinema`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinema`.`venda` (
  `idvenda` INT NOT NULL AUTO_INCREMENT,
  `idsessao` INT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`idvenda`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
